apiVersion: v1
kind: Secret
metadata:
  name: wireguard-secret
  namespace: wireguard
stringData:
  wg0.conf: |+
    [Interface]
    Address = {{ .Values.wireguard.address }}
    PrivateKey = {{ .Values.wireguard.privateKey }}
    ListenPort = {{ .Values.wireguard.internalPort }}
    
    [Peer]
    PublicKey = {{ .Values.wireguard.peer1.PublicKey }}
    PresharedKey = {{ .Values.wireguard.peer1.PresharedKey }}
    AllowedIPs = {{ .Values.wireguard.peer1.AllowedIPs }}

    [Peer]
    PublicKey = {{ .Values.wireguard.peer2.PublicKey }}
    PresharedKey = {{ .Values.wireguard.peer2.PresharedKey }}
    AllowedIPs = {{ .Values.wireguard.peer2.AllowedIPs }}

    [Peer]
    PublicKey = {{ .Values.wireguard.peer3.PublicKey }}
    PresharedKey = {{ .Values.wireguard.peer3.PresharedKey }}
    AllowedIPs = {{ .Values.wireguard.peer3.AllowedIPs }}
